# Generated by Django 5.0.6 on 2026-07-07 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=90, unique=True)),
                ('icon_class', models.CharField(blank=True, help_text="Optional Bootstrap Icons class, e.g. 'bi-egg-fried'", max_length=50)),
                ('order', models.PositiveIntegerField(default=0, help_text='Controls display order on the menu page')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in INR', max_digits=8)),
                ('image', models.ImageField(blank=True, null=True, upload_to='food_images/')),
                ('image_url', models.URLField(blank=True, help_text='Fallback image URL (e.g. an Unsplash link) if no file is uploaded.')),
                ('dietary_type', models.CharField(choices=[('veg', 'Vegetarian'), ('vegan', 'Vegan'), ('non_veg', 'Non-Vegetarian')], default='veg', max_length=10)),
                ('is_available', models.BooleanField(default=True, help_text='Uncheck to hide from the live menu (out of stock)')),
                ('is_featured', models.BooleanField(default=False, help_text="Show in the homepage 'Popular Dishes' carousel")),
                ('spice_level', models.PositiveSmallIntegerField(default=0, help_text='0 = none, 3 = very spicy')),
                ('prep_time_minutes', models.PositiveIntegerField(default=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu.category')),
            ],
            options={
                'ordering': ['category__order', 'name'],
            },
        ),
    ]
